2023-05-08 22:47:54,594 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.70.213.26:40656'
2023-05-08 22:47:57,649 - distributed.worker - INFO -       Start worker at:   tcp://10.70.213.26:37861
2023-05-08 22:47:57,649 - distributed.worker - INFO -          Listening to:   tcp://10.70.213.26:37861
2023-05-08 22:47:57,649 - distributed.worker - INFO -           Worker name:           SLURMCluster-109
2023-05-08 22:47:57,649 - distributed.worker - INFO -          dashboard at:         10.70.213.26:41292
2023-05-08 22:47:57,649 - distributed.worker - INFO - Waiting to connect to:    tcp://10.70.211.9:42768
2023-05-08 22:47:57,649 - distributed.worker - INFO - -------------------------------------------------
2023-05-08 22:47:57,649 - distributed.worker - INFO -               Threads:                          1
2023-05-08 22:47:57,649 - distributed.worker - INFO -                Memory:                  17.70 GiB
2023-05-08 22:47:57,650 - distributed.worker - INFO -       Local Directory: /opt/tmp/tmp/dask-worker-space/worker-xobeiw8j
2023-05-08 22:47:57,650 - distributed.worker - INFO - -------------------------------------------------
2023-05-08 22:47:59,330 - distributed.worker - INFO -         Registered to:    tcp://10.70.211.9:42768
2023-05-08 22:47:59,330 - distributed.worker - INFO - -------------------------------------------------
2023-05-08 22:47:59,330 - distributed.core - INFO - Starting established connection to tcp://10.70.211.9:42768
Matplotlib created a temporary config/cache directory at /opt/tmp/tmp/matplotlib-k62r6yl9 because the default path (/home/vlecoz/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
2023-05-08 22:48:08,090 - distributed.core - INFO - Event loop was unresponsive in Worker for 8.74s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
  0%|          | 0/9 [00:00<?, ?it/s] 22%|██▏       | 2/9 [00:00<00:00, 11.92it/s] 44%|████▍     | 4/9 [00:00<00:00, 12.18it/s] 67%|██████▋   | 6/9 [00:00<00:00, 11.37it/s] 89%|████████▉ | 8/9 [00:00<00:00, 10.52it/s]100%|██████████| 9/9 [00:00<00:00, 10.71it/s]
  0%|          | 0/50 [00:00<?, ?it/s]100%|██████████| 50/50 [00:00<00:00, 903944.83it/s]
0it [00:00, ?it/s]73it [00:00, 14994.33it/s]
  0%|          | 0/9 [00:00<?, ?it/s]100%|██████████| 9/9 [00:00<00:00, 1383.50it/s]
  0%|          | 0/8 [00:00<?, ?it/s]/mnt/live/user/vlecoz/Secured_interbank_network/emp_metrics.py:28: RuntimeWarning: invalid value encountered in long_scalars
  np.logical_and(
100%|██████████| 8/8 [00:00<00:00, 10827.50it/s]
  0%|          | 0/8 [00:00<?, ?it/s]100%|██████████| 8/8 [00:00<00:00, 4059.82it/s]
  0%|          | 0/8 [00:00<?, ?it/s]100%|██████████| 8/8 [00:00<00:00, 4001.24it/s]
  0%|          | 0/10 [00:00<?, ?it/s]  0%|          | 0/10 [00:00<?, ?it/s]
2023-05-08 22:48:11,882 - distributed.worker - WARNING - Compute Failed
Key:       single_run-c8d87222-0318-4ca3-b265-cc2d57158418
Function:  execute_task
args:      ((<function apply at 0x7fcfe111b040>, <function single_run at 0x7fcfbf119310>, [], (<class 'dict'>, [['nb_banks', 50], ['alpha_init', 0.16], ['alpha', 0.01], ['beta_init', 0.5], ['beta_reg', 0.5], ['beta_star', 0.5], ['gamma', 0.03], ['collateral_value', 1.0], ['initialization_method', 'pareto'], ['alpha_pareto', 1.3], ['shocks_method', 'non-conservative'], ['shocks_law', 'normal-mean-reverting'], ['shocks_vol', 0.05], ['result_location', './results/multiple_run/alpha_init/0.16/'], ['min_repo_trans_size', 1e-08], ['nb_steps', 10], ['dump_period', 10], ['plot_period', 10], ['cp_option', False], ['LCR_mgt_opt', False]])))
kwargs:    {}
Exception: "ValueError('zero-size array to reduction operation minimum which has no identity')"

slurmstepd: error: *** JOB 16609336 ON srv006955 CANCELLED AT 2023-05-08T22:48:20 ***
