2023-05-08 22:47:51,455 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.67.203.17:34334'
2023-05-08 22:47:54,736 - distributed.worker - INFO -       Start worker at:   tcp://10.67.203.17:42300
2023-05-08 22:47:54,736 - distributed.worker - INFO -          Listening to:   tcp://10.67.203.17:42300
2023-05-08 22:47:54,736 - distributed.worker - INFO -           Worker name:            SLURMCluster-98
2023-05-08 22:47:54,736 - distributed.worker - INFO -          dashboard at:         10.67.203.17:45430
2023-05-08 22:47:54,736 - distributed.worker - INFO - Waiting to connect to:    tcp://10.70.211.9:42768
2023-05-08 22:47:54,737 - distributed.worker - INFO - -------------------------------------------------
2023-05-08 22:47:54,737 - distributed.worker - INFO -               Threads:                          1
2023-05-08 22:47:54,737 - distributed.worker - INFO -                Memory:                  17.70 GiB
2023-05-08 22:47:54,737 - distributed.worker - INFO -       Local Directory: /opt/tmp/tmp/dask-worker-space/worker-dfaquwrr
2023-05-08 22:47:54,737 - distributed.worker - INFO - -------------------------------------------------
2023-05-08 22:47:58,198 - distributed.worker - INFO -         Registered to:    tcp://10.70.211.9:42768
2023-05-08 22:47:58,198 - distributed.worker - INFO - -------------------------------------------------
2023-05-08 22:47:58,199 - distributed.core - INFO - Starting established connection to tcp://10.70.211.9:42768
Matplotlib created a temporary config/cache directory at /opt/tmp/tmp/matplotlib-4xu2fzlt because the default path (/home/vlecoz/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
2023-05-08 22:48:08,100 - distributed.core - INFO - Event loop was unresponsive in Worker for 9.78s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
  0%|          | 0/9 [00:00<?, ?it/s] 22%|██▏       | 2/9 [00:00<00:00, 13.07it/s] 44%|████▍     | 4/9 [00:00<00:00, 13.08it/s] 67%|██████▋   | 6/9 [00:00<00:00, 13.10it/s] 89%|████████▉ | 8/9 [00:00<00:00, 13.15it/s]100%|██████████| 9/9 [00:00<00:00, 13.13it/s]
  0%|          | 0/50 [00:00<?, ?it/s]100%|██████████| 50/50 [00:00<00:00, 812849.61it/s]
0it [00:00, ?it/s]0it [00:00, ?it/s]
  0%|          | 0/9 [00:00<?, ?it/s]100%|██████████| 9/9 [00:00<00:00, 1307.59it/s]
  0%|          | 0/8 [00:00<?, ?it/s]/mnt/live/user/vlecoz/Secured_interbank_network/emp_metrics.py:28: RuntimeWarning: invalid value encountered in long_scalars
  np.logical_and(
100%|██████████| 8/8 [00:00<00:00, 10258.16it/s]
  0%|          | 0/8 [00:00<?, ?it/s]100%|██████████| 8/8 [00:00<00:00, 3897.60it/s]
  0%|          | 0/8 [00:00<?, ?it/s]100%|██████████| 8/8 [00:00<00:00, 4048.56it/s]
  0%|          | 0/10 [00:00<?, ?it/s]  0%|          | 0/10 [00:00<?, ?it/s]
2023-05-08 22:48:11,892 - distributed.worker - WARNING - Compute Failed
Key:       single_run-61e5aeaa-3cf0-4da4-b2eb-7ff2d48ae1e9
Function:  execute_task
args:      ((<function apply at 0x7fb1c45a5040>, <function single_run at 0x7fb1a6490040>, [], (<class 'dict'>, [['nb_banks', 50], ['alpha_init', 0.01], ['alpha', 0.01], ['beta_init', 0.01], ['beta_reg', 0.01], ['beta_star', 0.01], ['gamma', 0.03], ['collateral_value', 1.0], ['initialization_method', 'pareto'], ['alpha_pareto', 1.3], ['shocks_method', 'non-conservative'], ['shocks_law', 'normal-mean-reverting'], ['shocks_vol', 0.05], ['result_location', './results/multiple_run/beta_reg/0.01/'], ['min_repo_trans_size', 1e-08], ['nb_steps', 10], ['dump_period', 10], ['plot_period', 10], ['cp_option', False], ['LCR_mgt_opt', False]])))
kwargs:    {}
Exception: "ValueError('zero-size array to reduction operation minimum which has no identity')"

slurmstepd: error: *** JOB 16609234 ON srv007078 CANCELLED AT 2023-05-08T22:48:23 ***
