2023-05-08 22:47:51,398 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.67.203.13:42355'
2023-05-08 22:47:56,017 - distributed.worker - INFO -       Start worker at:   tcp://10.67.203.13:38403
2023-05-08 22:47:56,017 - distributed.worker - INFO -          Listening to:   tcp://10.67.203.13:38403
2023-05-08 22:47:56,017 - distributed.worker - INFO -           Worker name:           SLURMCluster-359
2023-05-08 22:47:56,017 - distributed.worker - INFO -          dashboard at:         10.67.203.13:46754
2023-05-08 22:47:56,017 - distributed.worker - INFO - Waiting to connect to:    tcp://10.70.211.9:42768
2023-05-08 22:47:56,017 - distributed.worker - INFO - -------------------------------------------------
2023-05-08 22:47:56,017 - distributed.worker - INFO -               Threads:                          1
2023-05-08 22:47:56,017 - distributed.worker - INFO -                Memory:                  17.70 GiB
2023-05-08 22:47:56,017 - distributed.worker - INFO -       Local Directory: /opt/tmp/tmp/dask-worker-space/worker-bh6ocuaz
2023-05-08 22:47:56,017 - distributed.worker - INFO - -------------------------------------------------
2023-05-08 22:47:59,664 - distributed.worker - INFO -         Registered to:    tcp://10.70.211.9:42768
2023-05-08 22:47:59,664 - distributed.worker - INFO - -------------------------------------------------
2023-05-08 22:47:59,665 - distributed.core - INFO - Starting established connection to tcp://10.70.211.9:42768
Matplotlib created a temporary config/cache directory at /opt/tmp/tmp/matplotlib-f96p343l because the default path (/home/vlecoz/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
2023-05-08 22:48:06,980 - distributed.core - INFO - Event loop was unresponsive in Worker for 7.29s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
  0%|          | 0/9 [00:00<?, ?it/s] 22%|██▏       | 2/9 [00:00<00:00, 12.29it/s] 44%|████▍     | 4/9 [00:00<00:00, 12.86it/s] 67%|██████▋   | 6/9 [00:00<00:00, 12.97it/s] 89%|████████▉ | 8/9 [00:00<00:00, 12.78it/s]100%|██████████| 9/9 [00:00<00:00, 12.76it/s]
  0%|          | 0/50 [00:00<?, ?it/s]100%|██████████| 50/50 [00:00<00:00, 803506.51it/s]
0it [00:00, ?it/s]8it [00:00, 5644.14it/s]
  0%|          | 0/9 [00:00<?, ?it/s]100%|██████████| 9/9 [00:00<00:00, 1496.18it/s]
  0%|          | 0/8 [00:00<?, ?it/s]/mnt/live/user/vlecoz/Secured_interbank_network/emp_metrics.py:28: RuntimeWarning: invalid value encountered in long_scalars
  np.logical_and(
100%|██████████| 8/8 [00:00<00:00, 7680.12it/s]
  0%|          | 0/8 [00:00<?, ?it/s]100%|██████████| 8/8 [00:00<00:00, 3390.02it/s]
  0%|          | 0/8 [00:00<?, ?it/s]100%|██████████| 8/8 [00:00<00:00, 3447.85it/s]
  0%|          | 0/10 [00:00<?, ?it/s]  0%|          | 0/10 [00:00<?, ?it/s]
2023-05-08 22:48:10,563 - distributed.worker - WARNING - Compute Failed
Key:       single_run-f365fee9-4bd1-4f51-94ef-305c0d672f7b
Function:  execute_task
args:      ((<function apply at 0x7fadf05e4040>, <function single_run at 0x7fadd227c700>, [], (<class 'dict'>, [['nb_banks', 50], ['alpha_init', 0.21], ['alpha', 0.01], ['beta_init', 0.5], ['beta_reg', 0.5], ['beta_star', 0.5], ['gamma', 0.03], ['collateral_value', 1.0], ['initialization_method', 'pareto'], ['alpha_pareto', 1.3], ['shocks_method', 'non-conservative'], ['shocks_law', 'normal-mean-reverting'], ['shocks_vol', 0.05], ['result_location', './results/multiple_run/alpha_init/0.21/'], ['min_repo_trans_size', 1e-08], ['nb_steps', 10], ['dump_period', 10], ['plot_period', 10], ['cp_option', False], ['LCR_mgt_opt', False]])))
kwargs:    {}
Exception: "ValueError('zero-size array to reduction operation minimum which has no identity')"

slurmstepd: error: *** JOB 16609199 ON srv007074 CANCELLED AT 2023-05-08T22:48:13 ***
